
development:
  adapter: postgresql
  encoding: utf8
  database: tweetsmithy-develop
  pool: 5

test: &TEST
  adapter: postgresql
  tncoding: utf8
  database: tweetsmithy-test
  pool: 4

production:
  adapter: postgresql
  encoding: utf8
  database: tweetsmithy
  pool: 5
